name: Lint

on: # yamllint disable-line rule:truthy
  push: null
  pull_request: null

permissions: {}

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Super-Linter
        uses: super-linter/super-linter@v9.0.0
